package com.github.damontecres.stashapp.ui.components

import android.icu.text.MessageFormat
import android.os.Build
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Delete
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.compose.ui.window.DialogProperties
import androidx.tv.material3.ButtonDefaults
import androidx.tv.material3.Icon
import androidx.tv.material3.MaterialTheme
import androidx.tv.material3.Text
import androidx.tv.material3.surfaceColorAtElevation
import com.github.damontecres.stashapp.R
import com.github.damontecres.stashapp.data.DataType
import com.github.damontecres.stashapp.ui.ComposeUiConfig
import com.github.damontecres.stashapp.ui.PreviewTheme
import com.github.damontecres.stashapp.ui.PreviewTvSpec
import com.github.damontecres.stashapp.ui.compat.Button
import com.github.damontecres.stashapp.ui.tryRequestFocus
import com.github.damontecres.stashapp.util.isNotNullOrBlank

/**
 * The PIN that gates permanent disk deletion. Prefer the read-only-mode PIN (its whole
 * purpose is gating destructive/management actions); fall back to the app PIN. Returns
 * null when no PIN is configured at all. Pure so it can be unit-tested.
 */
fun deleteGatePin(
    readOnlyPin: String?,
    appPin: String?,
): String? =
    when {
        readOnlyPin.isNotNullOrBlank() -> readOnlyPin
        appPin.isNotNullOrBlank() -> appPin
        else -> null
    }

private fun ComposeUiConfig.deleteGatePin(): String? =
    deleteGatePin(
        readOnlyPin = preferences.pinPreferences.readOnlyPin,
        appPin = preferences.pinPreferences.pin,
    )

@Composable
fun DeleteDialog(
    onDeleteConfirm: (deleteFiles: Boolean, deleteGenerated: Boolean) -> Unit,
    onDismissRequest: () -> Unit,
    dataType: DataType,
    name: String,
    files: List<String>,
    uiConfig: ComposeUiConfig,
) {
    val context = LocalContext.current
    var deleteGenerated by remember { mutableStateOf(true) }
    var deleteFiles by remember { mutableStateOf(false) }

    // The destructive "delete from disk" switch is hidden behind an explicit reveal so it
    // can never be toggled with a single D-pad press from the default dialog state.
    var showFileOption by remember { mutableStateOf(false) }

    // When deleting files, require a PIN (if one is set) before the destructive call runs.
    var awaitingPin by remember { mutableStateOf(false) }

    val focusRequester = remember { FocusRequester() }
    LaunchedEffect(awaitingPin) { focusRequester.tryRequestFocus() }

    val gatePin = uiConfig.deleteGatePin()

    val performDelete = {
        onDeleteConfirm.invoke(deleteFiles, deleteGenerated)
    }

    val onConfirmPressed = {
        if (deleteFiles && gatePin != null) {
            // Step into the PIN-gate before any delete_file=true mutation.
            awaitingPin = true
        } else {
            performDelete()
        }
    }

    Dialog(
        onDismissRequest = onDismissRequest,
        properties = DialogProperties(),
    ) {
        LazyColumn(
            modifier =
                Modifier
                    .background(
                        color = MaterialTheme.colorScheme.surfaceColorAtElevation(3.dp),
                        shape = RoundedCornerShape(16.dp),
                    ),
            contentPadding = PaddingValues(16.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp),
        ) {
            stickyHeader {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp),
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Icon(
                        imageVector = Icons.Default.Delete,
                        contentDescription = stringResource(R.string.stashapp_actions_delete),
                        tint = Color.Red,
                    )
                    Text(
                        text = stringResource(R.string.stashapp_actions_delete_entity, stringResource(dataType.stringId)) + ": $name",
                        style = MaterialTheme.typography.headlineSmall,
                        color = MaterialTheme.colorScheme.onSurface,
                        modifier = Modifier,
                    )
                }
            }

            if (awaitingPin) {
                // PIN-gate step: nothing destructive runs until the correct PIN is entered.
                item {
                    PinGate(
                        requiredPin = gatePin!!,
                        focusRequester = focusRequester,
                        onCorrect = { performDelete() },
                        onIncorrect = {
                            Toast.makeText(context, "Incorrect PIN", Toast.LENGTH_SHORT).show()
                        },
                    )
                }
                item {
                    Button(
                        onClick = { awaitingPin = false },
                        enabled = true,
                    ) {
                        Text(text = stringResource(R.string.stashapp_actions_cancel))
                    }
                }
                return@LazyColumn
            }

            item {
                val result =
                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                        MessageFormat(stringResource(R.string.stashapp_dialogs_delete_entity_desc))
                            .format(
                                mapOf(
                                    "count" to 1,
                                    "singularEntity" to stringResource(dataType.stringId),
                                    "pluralEntity" to stringResource(dataType.pluralStringId),
                                ),
                            )
                    } else {
                        "Are you sure you want to delete this?"
                    }
                Text(
                    text = result,
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onSurface,
                    modifier = Modifier,
                )
            }
            if (deleteFiles && files.isNotEmpty()) {
                item {
                    Box(
                        modifier = Modifier.background(MaterialTheme.colorScheme.errorContainer.copy(alpha = .5f)),
                    ) {
                        Column(
                            modifier =
                                Modifier
                                    .fillMaxWidth()
                                    .padding(8.dp)
                                    .animateItem(),
                        ) {
                            val result =
                                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                                    MessageFormat(stringResource(R.string.stashapp_dialogs_delete_alert))
                                        .format(
                                            mapOf(
                                                "count" to files.size,
                                                "singularEntity" to stringResource(R.string.stashapp_file),
                                                "pluralEntity" to stringResource(R.string.stashapp_files),
                                            ),
                                        )
                                } else {
                                    "The following files will be deleted:"
                                }
                            Text(
                                text = result,
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onSurface,
                                modifier = Modifier,
                            )
                            Text(
                                text = stringResource(R.string.delete_files_permanent_warning),
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.onErrorContainer,
                                modifier = Modifier.padding(top = 4.dp),
                            )
                            files.forEachIndexed { index, v ->
                                Text(
                                    text = "${index + 1}. $v",
                                    style = MaterialTheme.typography.bodySmall,
                                    color = MaterialTheme.colorScheme.onSurface,
                                    modifier = Modifier.padding(start = 8.dp),
                                )
                            }
                        }
                    }
                }
            }
            // The "delete from disk" switch only appears after the user deliberately reveals it.
            if (showFileOption) {
                item {
                    SwitchWithLabel(
                        label = stringResource(R.string.stashapp_actions_delete_file),
                        checked = deleteFiles,
                        onStateChange = { deleteFiles = it },
                        modifier = Modifier,
                    )
                }
            } else {
                item {
                    Button(
                        onClick = { showFileOption = true },
                        enabled = true,
                        colors =
                            ButtonDefaults.colors(
                                containerColor = MaterialTheme.colorScheme.errorContainer,
                            ),
                    ) {
                        Text(
                            text = stringResource(R.string.delete_show_file_option),
                            color = MaterialTheme.colorScheme.onErrorContainer,
                        )
                    }
                }
            }
            item {
                SwitchWithLabel(
                    label = stringResource(R.string.stashapp_actions_delete_generated_supporting_files),
                    checked = deleteGenerated,
                    onStateChange = { deleteGenerated = it },
                    modifier = Modifier,
                )
            }
            item {
                Row(
                    horizontalArrangement = Arrangement.SpaceEvenly,
                    modifier = Modifier.fillMaxWidth(),
                ) {
                    Button(
                        onClick = onDismissRequest,
                        enabled = true,
                        modifier = Modifier.focusRequester(focusRequester),
                    ) {
                        Text(
                            text = stringResource(R.string.stashapp_actions_cancel),
                        )
                    }
                    Button(
                        onClick = onConfirmPressed,
                        enabled = deleteGenerated || deleteFiles,
                        colors =
                            ButtonDefaults.colors(
                                containerColor = MaterialTheme.colorScheme.errorContainer,
                            ),
                    ) {
                        Text(
                            text =
                                if (deleteFiles) {
                                    stringResource(R.string.delete_confirm_files)
                                } else {
                                    stringResource(R.string.stashapp_actions_delete)
                                },
                            color = MaterialTheme.colorScheme.onErrorContainer,
                        )
                    }
                }
            }
        }
    }
}

@Composable
private fun PinGate(
    requiredPin: String,
    focusRequester: FocusRequester,
    onCorrect: () -> Unit,
    onIncorrect: () -> Unit,
) {
    var enteredPin by remember { mutableStateOf("") }
    val validateAndGo = {
        if (enteredPin == requiredPin) onCorrect() else onIncorrect()
    }
    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(
            text = stringResource(R.string.delete_enter_pin_to_confirm),
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onErrorContainer,
        )
        EditTextBox(
            modifier = Modifier.focusRequester(focusRequester),
            value = enteredPin,
            onValueChange = { enteredPin = it },
            keyboardOptions =
                KeyboardOptions(
                    keyboardType = KeyboardType.NumberPassword,
                    autoCorrectEnabled = false,
                    imeAction = ImeAction.Go,
                ),
            keyboardActions = KeyboardActions(onGo = { validateAndGo() }),
        )
        Button(
            onClick = validateAndGo,
            enabled = enteredPin.isNotEmpty(),
            colors =
                ButtonDefaults.colors(
                    containerColor = MaterialTheme.colorScheme.errorContainer,
                ),
        ) {
            Text(
                text = stringResource(R.string.delete_confirm_files),
                color = MaterialTheme.colorScheme.onErrorContainer,
            )
        }
    }
}

@Composable
@PreviewTvSpec
private fun DeleteDialogPreview() {
    PreviewTheme {
        DeleteDialog(
            onDeleteConfirm = { _, _ -> },
            onDismissRequest = {},
            dataType = DataType.SCENE,
            name = "This is the scene name",
            files = listOf("file1", "file2"),
            uiConfig = com.github.damontecres.stashapp.ui.uiConfigPreview,
        )
    }
}
